name: isoweek
description: A lightweight Dart package which provides the class Week (based on the ISO 8601 format).
version: 1.1.3
homepage: https://jensbecker.dev
repository: https://github.com/devj3ns/isoweek
issue_tracker: https://github.com/devj3ns/isoweek/issues

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  equatable: ^2.0.3

dev_dependencies:
  test: ^1.17.8
  flutter_lints: ">=1.0.3 <3.0.0"
  dart_code_metrics: ^4.0.0